### ISSUE TITLE
Regarding the exe-inference.ipynb example

### ISSUE THREAD

**Issue by EmadAlamoudi** [covid19-model/simulator#1]
First, I would like to thanks you for making this agent-based simulator available with its detailed documentation. Second, I just want ask if there is a missing parameter in the example `exe-inference.ipynb` when calling the `make_loss_function`. Shouldn't we also pass the `num_sites` parameter?

Thanks again for your great works

**Comment by manuelgr** [comment]
We have fixed this. Let us know if you have further issues. Many thanks for using our simulator!
