### ISSUE TITLE
missing (?) time adjustment in asym->resi transition time

### ISSUE THREAD

**Issue by giovact** [covid19-model/simulator#10]
Hi! I have a question about the following function, that samples transition times for asymptomatic nodes to recovery:

https://github.com/covid19-model/simulator/blob/7f6a0a339b396d3576d3d8e4db05607f42755dfa/sim/lib/distributions.py#L134-L138

Is it possible that a multiplication factor from days to hours (`self.tadj`) is missing here?
Also because `median_asymp_to_resi` is expressed in days as well as all the other transition times parameters.

Thanks in advance!

**Comment by larslorch** [comment]
Hi! 
Thanks very much for pointing this out and looking at the code in detail. You are right, this is a mistake, I will push a hot fix now to the master branch.
