### ISSUE TITLE
Dataset in CoronaWhy Dataverse

### ISSUE THREAD

**Issue by geek80** [covid19-model/simulator#11]
Hello,

Your dataset was added to CoronaWhy (https://www.coronawhy.org/) Data Lake on Dataverse  as a piece of common COVID-19 dataframe http://datasets.coronawhy.org/dataset.xhtml?persistentId=doi:10.5072/FK2/QHKUFM

Would you be willing to help with maintenance of your dataset in Dataverse, e.g. adding the relevant metadata and keeping the dataset up-to-date? That will help to make the dataset findable and accessible for medical science community.

**Comment by larslorch** [comment]
Hi, this repository is not a dataset, but rather a simulator that uses other data, amongst others COVID-19 case counts in Germany as provided by the Robert Koch Institute (RKI). I think you might have misunderstood, as the dataset you added to CoronaWhy (RKI_COVID19.csv) is property of the RKI and should be credited to them.

**Comment by geek80** [comment]
Ok understood. Thank you.

**Comment by k-goncharova** [comment]
@larslorch thanks for your explanations. jfyi - we've made deaccession to this dataset from CoronaWhy Dataverse.
