### ISSUE TITLE
possible bug in defining tmax for pushing household exposures

### ISSUE THREAD

**Issue by odorgergo** [covid19-model/simulator#13]
Hi! I have a question about the tmax variable that is passed to the __push_household_exposure_infector_to_j function in dynamics.py:

https://github.com/covid19-model/simulator/blob/3369c664d214701a2085e97522960a5419e451bd/sim/lib/dynamics.py#L701-L702

It seams to me that if self.bernoulli_is_fatal[infector] is False, then tmax can be smaller than the current time, and this actually occurs fairly often while running the code (making household infections much less likely). There seems to be a similar issue in lines 762 and 1027. Can you please clarify this for me?

Thanks in advance!

**Comment by larslorch** [comment]
Hi! 
You indeed found a bug here. There is a parenthesis missing around then inner if-else statement. The line should read

```
tmax = (self.state_started_at['ipre'][infector] + self.delta_ipre_to_isym[infector] + 
    (self.delta_isym_to_dead[infector] if self.bernoulli_is_fatal[infector] else self.delta_isym_to_resi[infector]) )
```
and similarly for the other occurrences. We will fix this presently. 
Thanks a lot for the very close look at the code!
