### ISSUE TITLE
concurrent.futures.process issue

### ISSUE THREAD

**Issue by EmadAlamoudi** [covid19-model/simulator#2]
Hi again! When running the `experiments.ipynb` using a `mob_sitting` that is `tu_settings_10_10.pk`, meaning that the population is scaled down to 10x factor and sites is scaled down to 10x factor, I ran into the below error: 

`concurrent.futures.process.BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.`

Such error did not occurs when scaling down the population to 20x and 15x, only when scaling down the population to 10x (the sites is kept scaled down to 10x in all cases). any idea about why it occurs and how to solve it? Thanks in advance.

**Comment by larslorch** [comment]
Hi! We have never experienced this error when running experiments from `experiments.ipynb`.
However, I have seen a similar error being thrown when converting the notebook to `.py` and running the script (independent of the `mob_setting` used). 
In particular, in case you convert to `.py`, you have to add `if __name__ == "__main__":` at the top and run the code indented inside this if clause. 
If this is not what you are doing, we suggest you run an individual instance of `DiseaseModel` (not with parallel processing) to figure our if the model itself has an issue.

**Comment by EmadAlamoudi** [comment]
I run it using an instance of the `DiseaseModel` and then It turns out that the OS kills the process. 
```
Data last updated at:  13.04.2020, 00:00 Uhr
Data last updated at:  13.04.2020, 00:00 Uhr
Data last updated at:  13.04.2020, 00:00 Uhr
Empirical fatality rates per age group:   [0.0, 0.0, 0.0, 0.001430615164520744, 0.00964630225080386, 0.11728395061728394]
runnung the simulator .... 
t: 394.96 | 408.00 hrs (17 d)
Process finished with exit code 137 (interrupted by signal 9: SIGKILL)
```

This may explains what happen when using the parallel simulation, that the OS would kill the process because of the excessive memory usage. I ran the script using a laptop of i7 processor with 16GB RAM. maybe I need to run it in large cluster?

**Comment by larslorch** [comment]
It is quite possible that you ran out of memory because the `MobilitySimulator` used to much memory, that would also explain why it happens for `tu_settings_10_10.pk` only, i.e. for less downscaling.

**Comment by manuelgr** [comment]
Soon we will update the simulator with a more efficient/faster version, which will likely solve this issue. We will keep you posted.

**Comment by EmadAlamoudi** [comment]
Sounds great. Thanks for the reply!
