### ISSUE TITLE
[Minor] Document "24" as "hours per day"

### ISSUE THREAD

**Issue by blakeelias** [covid19-model/simulator#8]
In this line:
https://github.com/covid19-model/simulator/blob/940383edc0c2f8c508a597b6037cd70c7f033357/sim/lib/inference.py#L183

The number 24.0 could be made more clear as being the number of hours in a day.
In general, unit conversions in code can easily become error-prone when treated just as numbers. 

At the very least, better to have some sort of constant like DAY_TO_HOURS = 24.0.
Even better, use a library like https://pint.readthedocs.io/en/0.11/ to handle units in an explicit way.

**Comment by larslorch** [comment]
Thanks for the suggestion, we will have this changed in the next push to master.
